FROM python:3.12-slim

WORKDIR /app

# ставим зависимости только для бота
COPY requirements-bot.txt ./
RUN pip install --no-cache-dir -r requirements-bot.txt

# копируем весь код
COPY . /app

# запускаем бота
CMD ["python", "bot.py"]
