FROM python:3.12-slim

WORKDIR /app

# ставим зависимости только для api
COPY requirements-api.txt ./
RUN pip install --no-cache-dir -r requirements-api.txt

# копируем весь код
COPY . /app

# запускаем FastAPI-сервис
CMD ["uvicorn", "notify_service:app", "--host", "0.0.0.0", "--port", "8000"]
